### ISSUE TITLE
chrome.runtime.onStartup && chrome.runtime.onInstalled undefined in content.js

### ISSUE THREAD

**Issue by dzgcsmthmt** [isaurssaurav/hot-reload-extension-vite-plugin#11]
in background and panel index.js,it is ok,but in content.js,chrome.runtime.onStartup && chrome.runtime.onInstalled undefined

**Comment by dzgcsmthmt** [comment]
config:
hotReloadExtension({
      log: true,
      backgroundPath: 'src/pages/content/index.ts'
}),
![error](https://github.com/isaurssaurav/hot-reload-extension-vite-plugin/assets/17973788/c6800683-d853-484f-bf75-e8962fa0f7f8)

**Comment by isaurssaurav** [comment]
Hey @dzgcsmthmt,
 
 `backgroundPath`  in config should always point to server worker file. It is where reload function should be injected.
 
 As for the content script to reload, You should build the content script file on the `vite.config.ts` where you have `hot-reload-extension-vite-plugin` initialised with  `backgroundPath` pointing to service worker file. Then, the plugin will detect change in content script file and reload the extension.
 
Here is the [example](https://github.com/isaurssaurav/hot-reload-extension-vite-plugin/tree/main/example) where reloading in content script works. Please check vite.config.ts on this example project.
 
 There may be some complex scenario which this plugin might not have covered. If so, I am happy to extend as required.
