### ISSUE TITLE
 popup reset

### ISSUE THREAD

**Issue by Coffee-Hot** [isaurssaurav/hot-reload-extension-vite-plugin#6]
good afternoon. Help me how to do a popup reset

**Comment by isaurssaurav** [comment]
@Coffee-Hot 
I assume you mean refresh the popup. if so, it already in [example](https://github.com/isaurssaurav/hot-reload-extension-vite-plugin/tree/main/example) directory. 

1. Follow the Usage step and load the extension in browser.
2. Change something in [popup file](https://github.com/isaurssaurav/hot-reload-extension-vite-plugin/blob/main/example/src/pages/popup/popup.vue).

If you open the popup, you should see the changes.
